//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticsRomania.Repository.Seeders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CountiesData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountiesData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StatisticsRomania.Repository.Seeders.CountiesData", typeof(CountiesData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 3648 3849 3966 3949 3970 3988 4187 4090&quot;,
        ///&quot;2018 1 Arad 3650 3621 3804 3837 3847 3997 3854 3804&quot;,
        ///&quot;2018 1 Arges 3786 3747 3891 4248 4350 4163 4416 4025&quot;,
        ///&quot;2018 1 Bacau 3680 3536 3925 3820 4007 3967 3904 4148&quot;,
        ///&quot;2018 1 Bihor 3358 3355 3585 3592 3661 3681 3688 3660&quot;,
        ///&quot;2018 1 BistritaNasaud 3320 3190 3477 3434 3476 3489 3496 3440&quot;,
        ///&quot;2018 1 Botosani 3228 3229 3532 3522 3483 3442 3410 3592&quot;,
        ///&quot;2018 1 Brasov 3978 4040 4344 4383 4290 4465 4280 4280&quot;,
        ///&quot;2018 1 Braila 3372 3300 3529 3613 3582 3563  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AverageGrossSalarySeeder {
            get {
                return ResourceManager.GetString("AverageGrossSalarySeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 2201 2325 2403 2384 2401 2400 2520 2456&quot;,
        ///&quot;2018 1 Arad 2196 2189 2299 2315 2324 2408 2318 2287&quot;,
        ///&quot;2018 1 Arges 2282 2271 2356 2566 2626 2518 2654 2422&quot;,
        ///&quot;2018 1 Bacau 2213 2138 2379 2300 2417 2391 2345 2490&quot;,
        ///&quot;2018 1 Bihor 2009 2018 2154 2154 2195 2207 2209 2191&quot;,
        ///&quot;2018 1 BistritaNasaud 2000 1935 2105 2077 2106 2115 2113 2078&quot;,
        ///&quot;2018 1 Botosani 1948 1950 2129 2122 2092 2070 2052 2150&quot;,
        ///&quot;2018 1 Brasov 2384 2437 2622 2636 2584 2687 2575 2575&quot;,
        ///&quot;2018 1 Braila 2033 2003 2130 2179 2161 2146  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AverageNetSalarySeeder {
            get {
                return ResourceManager.GetString("AverageNetSalarySeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 203097 206545 219819 211533 221001 226113&quot;,
        ///&quot;2018 1 Arad 306150 304446 324600 291652 355615 312298&quot;,
        ///&quot;2018 1 Arges 540896 528509 571945 510049 575925 555177&quot;,
        ///&quot;2018 1 Bacau 47847 49122 52077 45048 56858 49929&quot;,
        ///&quot;2018 1 Bihor 140345 156697 169785 134688 157435 168699&quot;,
        ///&quot;2018 1 BistritaNasaud 69877 66122 76492 64411 71431 71041&quot;,
        ///&quot;2018 1 Botosani 31231 26805 30890 24537 29893 27023&quot;,
        ///&quot;2018 1 Brasov 279719 287182 324297 287728 316732 320984&quot;,
        ///&quot;2018 1 Braila 25300 24522 33880 27934 36794 34 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportFobSeeder {
            get {
                return ResourceManager.GetString("ExportFobSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 173921 168596 209763 162692 169709 209871&quot;,
        ///&quot;2018 1 Arad 261055 259555 283756 253177 286090 282087&quot;,
        ///&quot;2018 1 Arges 388836 397479 419273 396978 427365 416701&quot;,
        ///&quot;2018 1 Bacau 60067 62193 74310 67631 79628 80901&quot;,
        ///&quot;2018 1 Bihor 149212 144475 155660 148142 165837 162159&quot;,
        ///&quot;2018 1 BistritaNasaud 53914 56803 61863 53123 53872 61434&quot;,
        ///&quot;2018 1 Botosani 21983 21586 26406 22072 25190 26165&quot;,
        ///&quot;2018 1 Brasov 249203 255022 281412 252157 276184 283064&quot;,
        ///&quot;2018 1 Braila 12331 12842 23560 19528 18352 20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportCifSeeder {
            get {
                return ResourceManager.GetString("ImportCifSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 93175 93840 94497 94588 94771 94940 95053 94933&quot;,
        ///&quot;2018 1 Arad 134294 135219 136132 136264 136527 136770 136934 136760&quot;,
        ///&quot;2018 1 Arges 156896 158247 159584 159737 160041 160323 160513 160312&quot;,
        ///&quot;2018 1 Bacau 110999 111806 112604 112712 112926 113126 113259 113118&quot;,
        ///&quot;2018 1 Bihor 172282 173854 175411 175577 175907 176214 176419 176201&quot;,
        ///&quot;2018 1 BistritaNasaud 70307 70868 71424 71492 71629 71756 71840 71750&quot;,
        ///&quot;2018 1 Botosani 55483 55773 56057 56112 56221 56322 56390 56318&quot;,
        ///&quot;2018 1 Brasov  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberOfEmployeesSeeder {
            get {
                return ResourceManager.GetString("NumberOfEmployeesSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 17186 17023 18256 23360 30154 36144 46409 56314&quot;,
        ///&quot;2018 1 Arad 19427 19737 23004 24866 32157 35615 42610 46219&quot;,
        ///&quot;2018 1 Arges 21970 23677 24465 25534 28513 33272 48585 53817&quot;,
        ///&quot;2018 1 Bacau 15972 18085 17832 22395 28042 34030 39150 53517&quot;,
        ///&quot;2018 1 Bihor 66520 61300 71972 82782 100943 145676 203180 228748&quot;,
        ///&quot;2018 1 BistritaNasaud 8199 7760 10032 11473 14748 17425 24926 35643&quot;,
        ///&quot;2018 1 Botosani 5536 4621 5303 5939 5795 7589 7969 9887&quot;,
        ///&quot;2018 1 Brasov 233925 213648 152709 166700 183411 202 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberOfNightsSeeder {
            get {
                return ResourceManager.GetString("NumberOfNightsSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 8728 8674 10675 12797 17520 20369 23158 27352&quot;,
        ///&quot;2018 1 Arad 13224 12824 14374 15280 18805 19320 23502 26389&quot;,
        ///&quot;2018 1 Arges 13693 13726 14484 16466 17848 21651 29965 35312&quot;,
        ///&quot;2018 1 Bacau 7964 8488 9088 11315 12807 13180 14330 19465&quot;,
        ///&quot;2018 1 Bihor 32624 28559 32721 36880 42789 50927 64853 78540&quot;,
        ///&quot;2018 1 BistritaNasaud 5276 5123 6973 7804 10177 11234 13612 17637&quot;,
        ///&quot;2018 1 Botosani 3676 3013 3508 3728 3647 4284 4430 5011&quot;,
        ///&quot;2018 1 Brasov 107046 103591 81660 88413 102660 110831 135622 16 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NumberOfTouristsSeeder {
            get {
                return ResourceManager.GetString("NumberOfTouristsSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 29176 37949 10056 48841 51292 16242&quot;,
        ///&quot;2018 1 Arad 45095 44891 40844 38475 69525 30211&quot;,
        ///&quot;2018 1 Arges 152060 131030 152672 113071 148560 138476&quot;,
        ///&quot;2018 1 Bacau -12220 -13071 -22233 -22583 -22770 -30972&quot;,
        ///&quot;2018 1 Bihor -8867 12222 14125 -13454 -8402 6540&quot;,
        ///&quot;2018 1 BistritaNasaud 15963 9319 14629 11288 17559 9607&quot;,
        ///&quot;2018 1 Botosani 9248 5219 4484 2465 4703 858&quot;,
        ///&quot;2018 1 Brasov 30516 32160 42885 35571 40548 37920&quot;,
        ///&quot;2018 1 Braila 12969 11680 10320 8406 18442 14842&quot;,
        ///&quot;2018 1 Buzau 21620 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SoldFobCifSeeder {
            get {
                return ResourceManager.GetString("SoldFobCifSeeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;2018 1 Alba 6105 6454 6447 5951 5701 5608 5679 5690&quot;,
        ///&quot;2018 1 Arad 3077 3017 3015 2731 2681 2733 2876 2859&quot;,
        ///&quot;2018 1 Arges 10411 10332 9740 8936 8734 8824 8949 8822&quot;,
        ///&quot;2018 1 Bacau 14107 13938 13513 12918 12726 12867 12994 12947&quot;,
        ///&quot;2018 1 Bihor 6328 6063 5940 5562 5448 5476 3803 4144&quot;,
        ///&quot;2018 1 BistritaNasaud 4096 4062 3844 3544 3317 3266 3342 3395&quot;,
        ///&quot;2018 1 Botosani 4966 4878 4708 4071 3979 4007 4121 4146&quot;,
        ///&quot;2018 1 Brasov 7344 7164 7060 6566 6217 6394 6339 6331&quot;,
        ///&quot;2018 1 Braila 6410 6366 6188 5815  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnemployedSeeder {
            get {
                return ResourceManager.GetString("UnemployedSeeder", resourceCulture);
            }
        }
    }
}
